# Generated by Django 3.2.4 on 2021-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tmp/items')),
                ('file', models.FileField(blank=True, null=True, upload_to='tmp/files')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
