# Generated by Django 3.2.4 on 2021-09-20 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Desconto')),
                ('cupom', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=3)),
                ('validade', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='confirm.item', verbose_name='Item')),
            ],
        ),
    ]
