# Generated by Django 3.2.4 on 2021-09-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0002_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconto',
            name='no_cartao',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=3, null=True),
        ),
    ]
