# Generated by Django 3.2.4 on 2021-09-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0003_desconto_no_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconto',
            name='item_dois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descontoitem_dois_set', to='confirm.item', verbose_name='Item dois'),
        ),
        migrations.AlterField(
            model_name='desconto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desconto_item_set', to='confirm.item', verbose_name='Item'),
        ),
    ]
