# Generated by Django 3.2.4 on 2021-10-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0005_checkout_generalmanager_inventory_itemsale_shop_shoppingmall_town_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='desconto',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_desconto_set', to='confirm.town'),
        ),
        migrations.AlterField(
            model_name='shoppingmall',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_ShoppingMall_set', to='confirm.town'),
        ),
    ]
