# Generated by Django 3.2.4 on 2021-07-19 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('score', models.IntegerField(validators=[movies.models.validate_score], verbose_name='Score')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=1, verbose_name='Status')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data x')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='hora x')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data hora x')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.genre', verbose_name='Genre')),
            ],
        ),
    ]
