# Generated by Django 3.2.4 on 2021-07-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210719_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='newscore',
            new_name='new_score',
        ),
    ]
